### ISSUE TITLE
javax.crypto.BadPaddingException: Given final block not properly padded error with encrypted password

### ISSUE THREAD

**Issue by mbabari** [mbabari/SIDBMonitor#1]
javax.crypto.BadPaddingException: Given final block not properly padded

        at com.ibm.crypto.fips.provider.at.a(Unknown Source)

        at com.ibm.crypto.fips.provider.at.b(Unknown Source)

        at com.ibm.crypto.fips.provider.at.engineDoFinal(Unknown Source)

        at javax.crypto.Cipher.doFinal(Unknown Source)

        at com.support.SIDBMonitor.SecureString.decrypt(SecureString.java:62)

        at com.support.SIDBMonitor.SecureString.decrypt(SecureString.java:35)

        at com.support.SIDBMonitor.SIDBMonitor.main(SIDBMonitor.java:1163)

**Comment by mbabari** [comment]
Problem appears when FIPS is first provider used in the java security provider list.
Start the application with -Djava.security.properties to point to a modified java.security where FIPS is not the first provider.
