### ISSUE TITLE
SIDBMonitor SI database connection issue

### ISSUE THREAD

**Issue by srinitig** [mbabari/SIDBMonitor#2]
Hi, we have upgraded our environments to windows 2019. SI is wokring fine. only issue we have is SIDBMonitoring giving below error when i try to start

Output file: D:/IBM/SI/tools/output/SIDBMonitorReport.html
Found internal config file /com/sterlingcommerce/security/jcae/provider.txt, loading it now!
Done loading it.
ERROR: Connection failed please check your login details...
com.microsoft.sqlserver.jdbc.SQLServerException: The driver could not establish a secure connection to SQL Server using Secure Sockets Layer (SSL) encryption. Error: "SQL Server did not return a response. The connection has been disconnected ClientConnectionId:ff660a6e-ef26-4a0b-90b2-38db35cd2eae".
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:2670)
        at com.microsoft.sqlserver.jdbc.TDSChannel.enableSSL(IOBuffer.java:1837)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2257)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:1921)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:1762)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1077)
        at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:623)
        at java.sql.DriverManager.getConnection(DriverManager.java:675)
        at java.sql.DriverManager.getConnection(DriverManager.java:258)
        at com.support.SIDBMonitor.SIDBMonitor.main(SIDBMonitor.java:907)
Caused by: java.io.IOException: SQL Server returned no response. The connection has been disconnected. ClientConnectionId: ff660a6e-ef26-4a0b-90b2-38db35cd2eae
        at com.microsoft.sqlserver.jdbc.TDSChannel$SSLHandshakeInputStream.ensureSSLPayload(IOBuffer.java:780)
        at com.microsoft.sqlserver.jdbc.TDSChannel$SSLHandshakeInputStream.readInternal(IOBuffer.java:836)
        at com.microsoft.sqlserver.jdbc.TDSChannel$SSLHandshakeInputStream.read(IOBuffer.java:827)
        at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.readInternal(IOBuffer.java:1009)
        at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.read(IOBuffer.java:997)
        at com.ibm.jsse2.b.a(b.java:49)
        at com.ibm.jsse2.b.a(b.java:192)
        at com.ibm.jsse2.av.a(av.java:407)
        at com.ibm.jsse2.av.i(av.java:45)
        at com.ibm.jsse2.av.a(av.java:637)
        at com.ibm.jsse2.av.startHandshake(av.java:1020)
        at com.microsoft.sqlserver.jdbc.TDSChannel.enableSSL(IOBuffer.java:1767)
        ... 8 more
documentTotalSize: true
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 0
        at java.lang.String.substring(String.java:2726)
        at com.support.SIDBMonitor.SIDBMonitor.monitoringReportQueries(SIDBMonitor.java:508)
        at com.support.SIDBMonitor.SIDBMonitor.main(SIDBMonitor.java:935)

only change we did from previous configuration is that we started using jdbc6 and changed to point jar.

i am a bit new to this. can you please show some light what to check to make it work.

**Comment by mbabari** [comment]
Can you try the jtds driver

https://stackoverflow.com/questions/14229209/jdbc-error-while-connecting-to-sqlserver

**Comment by srinitig** [comment]
Hi, issue is resolved by adding below into url as properties
useSSL=false;trustServerCertificate=true;sslProtocol=TLSv1.2

**Comment by mbabari** [comment]
Excellent thanks for sharing!

**Comment by srinitig** [comment]
is there any document which gives detailed explanation of different reports, i have gone through the report it is good, but i still missing what action i shall take after reading report based on data that is reproted. if that an be updated, it will help most of them like me who are new

**Comment by mbabari** [comment]
[SIDBMonitor180.pdf](https://github.com/mbabari/SIDBMonitor/files/5407468/SIDBMonitor180.pdf)
The **full report** will give you different useful report about the health of your SI database.
For example the workflow_context per hour will give you an idea about your peak periods so you would shift your housekeeping to off-peak.
Top table info will report will give an idea about the number of rows of your top tables and when the statistics were last collected. If the DB stats are too old you will need to check with your DBA to correct.
Node statistics will give the load distribution across node and adapter containers. 
Tablespace statistics: will give an idea about the size/used/free/pct of different tblspaces. (Oracle /DB2 only)
There other Purge and housekeeping related reports also to help understand the distribution of housekeeping and act when there is DB growth.
After running the full report once and you understand your Database, you can use the **LW report** and schedule it daily to collect different counts and KPI. We have customers running the LW report (early) daily for years, it will show what tables are growing, stable or dropping in size, wether purge, index, halted, associate counts growing , the size of the DB (oracle and db2 only) etc... 

Thanks
