### ISSUE TITLE
java.security.NoSuchAlgorithmException: AES KeyGenerator not available

### ISSUE THREAD

**Issue by srinitig** [mbabari/SIDBMonitor#3]
Hi, when i try to encrypt password below error is coming., i have followed Issue 1 to override java security properties. 

java.security.NoSuchAlgorithmException: AES KeyGenerator not available
        at javax.crypto.KeyGenerator.<init>(Unknown Source)
        at javax.crypto.KeyGenerator.getInstance(Unknown Source)
        at com.support.SIDBMonitor.SecureString.getRawKey(SecureString.java:40)
        at com.support.SIDBMonitor.SecureString.decrypt(SecureString.java:33)
        at com.support.SIDBMonitor.SIDBMonitor.main(SIDBMonitor.java:846)
Output file: D:/IBM/SI/tools/output/SIDBMonitorReport.html
Exception in thread "main" java.lang.NullPointerException
        at java.security.SecureRandom.nextBytes(SecureRandom.java:471)
        at java.util.UUID.randomUUID(UUID.java:156)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2250)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:1921)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:1762)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1077)
        at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:623)
        at java.sql.DriverManager.getConnection(DriverManager.java:675)
        at java.sql.DriverManager.getConnection(DriverManager.java:258)
        at com.support.SIDBMonitor.SIDBMonitor.main(SIDBMonitor.java:907)

**Comment by mbabari** [comment]
Can you please post the list of -Djava.security.properties=<URL>

**Comment by srinitig** [comment]
[sidb-java.security.txt](https://github.com/mbabari/SIDBMonitor/files/5406059/sidb-java.security.txt)

**Comment by srinitig** [comment]
i just added .txt to upload

**Comment by srinitig** [comment]
%SI_JAVA% -Djava.security.properties==/jre/lib/security/sidb-java.security  -cp "%SI_TOOLS_JAR_DIR%/%DBMON_JAR_FILE%;%SI_DB_JAR%" com.support.SIDBMonitor.SIDBMonitor  -propFile %SI_TOOLS_PROP_DIR%/%DBMON_PROP_FILE% -outDir %DBMON_OUT_DIR% %FULL_REPORT%

**Comment by mbabari** [comment]
You can either use a Sun JDK to run this tool with encrypted password OR install a new provider  (JCE extension) to your IBM JDK.

This provider works:
security.provider.1=sun.security.provider.Sun
